### ISSUE TITLE
response.headers.getSetCookie

### ISSUE THREAD

**Issue by ondrejjcizek** [joshnuss/airbadge#1]
Hello, I have tried to follow docs but it when I want to use SvelteKitAuth in hooks.server.js this error message happens.

TypeError: response.headers.getSetCookie is not a function

**Comment by joshnuss** [comment]
Hi @ondrejjcizek!

What version of Node are you using?

Found this issue, which seems related:
https://github.com/nextauthjs/next-auth/issues/9763

**Comment by ondrejjcizek** [comment]
Hi @joshnuss!

Problem was Node 18

Node 20.10.0 works

Also, can happen this error =≥ `[auth][error] TypeError: "ikm"" must be an instance of Uint8Array or a string`
secret must be defined.
https://next-auth.js.org/getting-started/upgrade-v4#missing-secret

Finally working is it after defining `price, priceId` in plans.

**Comment by joshnuss** [comment]
Awesome!

Thanks @ondrejjcizek, glad it's figured out.

Please let me know if you run into anything else.
